-- 코드를 입력하세요
# SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, GENDER, COUNT(*) USERS
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, B.GENDER, COUNT( DISTINCT A.USER_ID) AS USERS
FROM ONLINE_SALE A
JOIN USER_INFO B
ON A.USER_ID = B.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
ORDER BY 1, 2, 3


# SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_INFO.GENDER, COUNT( DISTINCT ONLINE_SALE.USER_ID) AS USERS
# FROM ONLINE_SALE
# JOIN USER_INFO
# ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID AND
# GENDER IS NOT NULL
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER 
# ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE), USER_INFO.GENDER