-- 코드를 입력하세요
# SELECT YEAR(O.SALES_DATE) YEAR
SELECT YEAR(O.SALES_DATE) YEAR, MONTH(O.SALES_DATE) MONTH, COUNT(DISTINCT(O.USER_ID)) PUCHASED_USERS,
ROUND(COUNT(DISTINCT(o.USER_ID)) / (SELECT COUNT(u.USER_ID) FROM USER_INFO u WHERE DATE_FORMAT(u.JOINED, '%Y') = 2021), 1) PUCHASED_RATIO
FROM USER_INFO I, ONLINE_SALE O
WHERE I.USER_ID = O.USER_ID AND I.JOINED LIKE '2021%'
GROUP BY 1, 2
ORDER BY 1, 2

# SELECT DATE_FORMAT(o.SALES_DATE, '%Y') 'YEAR', 
#        DATE_FORMAT(o.SALES_DATE, '%m') 'MONTH', 
#        COUNT(DISTINCT(o.USER_ID)) 'PUCHASED_USERS',
#        ROUND(COUNT(DISTINCT(o.USER_ID)) / (SELECT COUNT(DISTINCT(u.USER_ID)) FROM USER_INFO u WHERE DATE_FORMAT(u.JOINED, '%Y') = 2021), 1) 'PUCHASED_RATIO'
# FROM ONLINE_SALE o, USER_INFO u
# WHERE o.USER_ID = u.USER_ID and DATE_FORMAT(u.JOINED, '%Y') = 2021
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH