-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
# SELECT *
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%'
AND B.SEX_UPON_OUTCOME NOT LIKE 'Intact%'
ORDER BY 1

# SELECT 
#     I.ANIMAL_ID,
#     I.ANIMAL_TYPE,
#     I.NAME
# FROM ANIMAL_INS I
#     JOIN ANIMAL_OUTS O
#         ON I.ANIMAL_ID = O.ANIMAL_ID
# WHERE I.SEX_UPON_INTAKE REGEXP ('Intact')
#     AND O.SEX_UPON_OUTCOME REGEXP ('Spayed|Neutered')
# ORDER BY 1
# ;