-- 코드를 입력하세요
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN JULY B
ON A.FLAVOR = B.FLAVOR
GROUP BY FLAVOR
ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3

# SELECT a.FLAVOR
# FROM FIRST_HALF a JOIN JULY b
# ON a.FLAVOR = b.FLAVOR
# GROUP BY FLAVOR
# ORDER BY SUM(a.TOTAL_ORDER + b.TOTAL_ORDER) DESC
# LIMIT 3