-- 코드를 입력하세요
# SELECT CAR_ID, IF(END_DATE > DATE('2022-10-16'), '대여중', '대여 가능') AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# GROUP BY CAR_ID
# ORDER BY 1 DESC

WITH A AS(
    SELECT
    CAR_ID, 
    '대여중' AS AVAILABILITY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
    )

SELECT 
    DISTINCT(C.CAR_ID),
    IFNULL(A.AVAILABILITY, '대여 가능')
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
LEFT JOIN A ON C.CAR_ID = A.CAR_ID
ORDER BY CAR_ID DESC;