-- 코드를 입력하세요
SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, D.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT A
RIGHT JOIN PATIENT P
ON P.PT_NO = A.PT_NO
LEFT JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
WHERE A.MCDP_CD = 'CS'
    AND APNT_CNCL_YN = 'N'
    AND DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13'
ORDER BY 6


# SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
# FROM APPOINTMENT AS A
# RIGHT JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
# LEFT JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
# WHERE APNT_CNCL_YN = 'N' AND
#       LEFT(APNT_YMD, 10) = '2022-04-13' AND
#       A.MCDP_CD = 'CS'
# ORDER BY APNT_YMD ASC