-- 코드를 입력하세요
SELECT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE CAR_TYPE = '세단'
    AND A.CAR_ID = B.CAR_ID
    AND START_DATE LIKE '%-10-%'
GROUP BY 1
ORDER BY 1 DESC