-- 코드를 입력하세요
SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(SUM(B.REVIEW_SCORE)/COUNT(*), 2) SCORE
FROM REST_INFO A, REST_REVIEW B
WHERE A.REST_ID = B.REST_ID
    AND A.ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY 6 DESC, 4 DESC